name: simple
on:
  workflow_dispatch:
  
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
      - name: Run a Script
        run: |
          echo: "I am running a job in the DEV environment"
        
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    steps:
      - uses: actions/checkout@v3
      - name: Run a Script
        run: |
          echo: "I am running a job in the QA environment"
          
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA
    steps:
      - uses: actions/checkout@v3
      - name: Run a Script
        run: |
          echo: "I am running a job in the PROD environment"
